### PR TITLE
Updated the secure auth tokens

### PR DESCRIPTION
**Pull request by AdamWard1995**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #none# - documentation fixes and/or test additions
- [X] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* **Updated** the secure auth tokens in `.travis.yml`

### CODE REVIEW

**Comment by juwara0** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/ciena-blueplanet/ember-validator-shim/pull-request/48/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-blueplanet/ember-validator-shim)

**Comment by sandersky** [comment]
@AdamWard1995 this pull request [failed to actually publish](https://travis-ci.org/ciena-blueplanet/ember-validator-shim/jobs/230824531). To fix it you need to add [this file](https://github.com/ciena-frost/ember-frost-core/blob/master/.pr-bumper.json).

**Comment by AdamWard1995** [comment]
@sandersky to the base directory of this repo?

**Comment by sandersky** [comment]
@AdamWard1995 yes

**Pull request merged**
